import React from 'react'
import "../IPRights/ip.css"

function TermsAndCondition() {
  return (
    <>
      <center>
        <div className="container">
          <div>
            <h2 style={{ fontSize: "30px",textAlign:"center" }}>
              FIDO DIDO WEBSITE TERMS AND CONDITIONS
            </h2>

            <p>
              <span className="important">
                FIDOLABS LLC (DOING BUSINESS AS “FIDO DIDO”)
              </span>{" "}
              EMBODYED THE COMMENCEMENT OF A NEW DIGITAL CHAPTER, EMBRACING THE
              GROWING ERA OF CO-CREATION AND CO-OWNERSHIP POWERED BY WEB3.AND
              COLLECTIONS OF NON-FUNGIBLE TOKENS (“NFT”) ON THE ETHEREUM
              BLOCKCHAIN, FEATURING UNIQUE AND ENGAGING DIGITAL ASSETS (“FIDO
              DIDO NFT”).
            </p>

            <p>
              <span className="important">
                THESE TERMS AND CONDITIONS (“TERMS”)
              </span>{" "}
              GOVERN THE RELATIONSHIP BETWEEN FIDO DIDO AND ANY PERSON (“USER”,
              “YOU”) ACCESSING AND/OR USING FIDO DIDO'S WEBSITE (
              <span className="important">WWW.FIDODIO.IO</span>, ALSO REFERRED
              TO HEREIN AS “FIDO DIDO WEBSITE”).
            </p>

            <p>
              <span className="important">
                PLEASE READ THESE TERMS CAREFULLY BEFORE USING THE FIDODIO.IO
                WEBSITE.
              </span>
            </p>

            <h2>1 CONDITIONS OF USE OF THE FIDO DIDO WEBSITE</h2>
            <p>
              <span className="important">
                THE FIDO DIDO WEBSITE IS INTENDED FOR USERS WHO ARE AT LEAST
                EIGHTEEN (18) YEARS OLD.
              </span>{" "}
              BY USING THE FIDO DIDO WEBSITE, YOU CONFIRM THAT YOU ARE AT LEAST
              EIGHTEEN (18) YEARS OLD AND HAVE READ AND ACCEPTED THESE TERMS
              EXHAUSTIVELY AND UNCONDITIONALLY.
            </p>

            <p>
              IF THE USER IS UNDER EIGHTEEN (18) YEARS OLD, THE USER UNDERTAKES
              TO OBTAIN THE PRIOR AND EXPRESS CONSENT OF HIS/HER PARENT OR LEGAL
              GUARDIAN TO USE THE FIDO DIDO WEBSITE AND TO REVIEW THE TERMS WITH
              THEM. THE PARENT OR LEGAL GUARDIAN OF A USER UNDER EIGHTEEN (18)
              YEARS OLD UNDERTAKES TO ABIDE BY THESE TERMS AND ACKNOWLEDGES
              BEING RESPONSIBLE FOR THE USER'S ACTIVITIES ON THE FIDO DIDO
              WEBSITE.
            </p>

            <p>
              IN CASE OF YOUR DISAGREEMENT, IN WHOLE OR IN PART, WITH THESE
              TERMS, YOU MUST IMMEDIATELY CEASE ANY AND ALL USE OF THE FIDO DIDO
              WEBSITE.
            </p>

            <h2>2. AMENDMENT TO THE TERMS</h2>

            <p>
              THE TERMS MAY BE UPDATED FROM TIME TO TIME AS FIDO DIDO DEEMS
              NECESSARY OR USEFUL.
            </p>

            <p>
              IF YOU DO NOT AGREE TO THE TERMS, INCLUDING AS MAY BE AMENDED, YOU
              SHALL CEASE ANY AND ALL UTILIZATION OF THE FIDO DIDO WEBSITE AND
              RELATED SERVICES.
            </p>

            <h2>3. ACCESS TO THE FIDO DIDO WEBSITE</h2>

            <p>
              YOU ARE PERSONALLY RESPONSIBLE FOR SETTING UP THE IT AND
              TELECOMMUNICATIONS RESOURCES REQUIRED TO ACCESS THE FIDO DIDO
              WEBSITE AND USE THE SERVICES. YOU SHALL BEAR THE COST OF
              TELECOMMUNICATIONS WHEN ACCESSING THE INTERNET TO USE THE FIDO
              DIDO WEBSITE.
            </p>

            <p>
              FIDO DIDO RESERVES THE RIGHT TO, WITHOUT NOTICE NOR COMPENSATION,
              TEMPORARILY OR PERMANENTLY, CLOSE THE FIDO DIDO WEBSITE OR ACCESS
              TO ONE OR MORE SERVICES TO PERFORM MAINTENANCE OPERATIONS. FIDO
              DIDO MAY CARRY OUT ANY CHANGES AND IMPROVEMENTS TO THE FIDO DIDO
              WEBSITE AND SERVICES THAT IT DEEMS NECESSARY.
            </p>

            <h2>4. SERVICES</h2>

            <h3>4.1 GENERAL SERVICES</h3>

            <p>
              THE FIDO DIDO WEBSITE PROVIDES ACCESS TO FUNCTIONALITIES,
              FEATURES, AND SERVICES RELATED TO FIDODIO.IO NFT COLLECTIONS AND
              COMMUNITY (THE “SERVICES”).
            </p>

            <p>
              ACCESS TO SOME SERVICES MAY ONLY BE AVAILABLE TO THE HOLDER OF A
              FIDO DIDO NFT AND REQUIRE PROOF OF OWNERSHIP BY CONNECTING A
              SUPPORTED BLOCKCHAIN-BASED DIGITAL WALLET TO THE FIDO DIDO WEBSITE
              (“DIGITAL WALLET”).
            </p>

            <p>
              DIGITAL WALLETS ARE THIRD-PARTY PRODUCTS AND SERVICES THAT ARE NOT
              AFFILIATED, IN ANY WAY WHATSOEVER, WITH FIDO DIDO NOR IN ITS
              CUSTODY OR CONTROL. ACCESS AND USE OF DIGITAL WALLETS ARE AT THE
              USER'S OWN RISK AND DISCRETION AND SUBJECT TO THEIR OWN APPLICABLE
              TERMS.
            </p>

            <p>
              YOU ARE SOLELY RESPONSIBLE FOR YOUR DIGITAL WALLET SECURITY,
              INCLUDING ASSOCIATED PASSWORDS, SEED WORDS, AND KEYS. FIDO DIDO
              SHALL NOT, IN ANY EVENT WHATSOEVER, BE HELD RESPONSIBLE FOR ANY
              RISK ASSOCIATED WITH YOUR ACCESS AND/OR USE OF A DIGITAL WALLET.
              IN THE EVENT YOU LOSE OR CAN NO LONGER ACCESS YOUR DIGITAL WALLET,
              FIDO DIDO CANNOT RETRIEVE YOUR FIDO DIDO NFT FROM YOUR DIGITAL
              WALLET.
            </p>
            <h2>4.2 NFT PRIMARY SALE SERVICES ON THE FIDO DIDO WEBSITE</h2>

            <p>
              FIDO DIDO MAY, IN ITS SOLE DISCRETION, PROVIDE ACCESS TO PRIMARY
              SALES OF FIDO DIDO NFTS THROUGH ONE OR SEVERAL OF THE FOLLOWING
              ACCESS RIGHTS: FREE MINT FOR HOLDERS OF A FIDO DIDO NFT, ALLOW
              LIST, AND/OR PUBLIC SALE.
            </p>

            <p>
              YOU WILL BE REQUIRED TO CONNECT YOUR DIGITAL WALLET TO THE FIDO
              DIDO WEBSITE IN ORDER TO, DEPENDING ON THE RIGHTS YOU HAVE BEEN
              GRANTED ON THE PRIMARY SALE, (I) WHERE APPLICABLE, CONFIRM YOUR
              CURRENT OWNERSHIP OF A FIDO DIDO NFT, AND/OR (II) WHERE
              APPLICABLE, TRANSFER TO FIDO DIDO THE APPLICABLE PURCHASE PRICE,
              AND (III) RECEIVE AN NFT.
            </p>

            <p>
              APPLICABLE PURCHASE PRICE OF A FIDO DIDO NFT ARE SET FORTH ON THE
              FIDO DIDO WEBSITE AND ARE BINDING AT THE TIME OF PURCHASE.
              ADDITIONAL FEES (INCLUDING GAS FEES) MAY BE REQUIRED AT THE TIME
              OF PURCHASE TO COMPLETE THE SALE. FIDO DIDO DOES NOT MONITOR NOR
              BENEFIT FROM THESE FEES.
            </p>

            <p>
              FIDO DIDO WILL DIRECTLY TRANSFER THE FIDO DIDO NFT YOU ACQUIRED TO
              THE SUPPORTED DIGITAL WALLET YOU CONNECTED TO THE FIDO DIDO
              WEBSITE, DEPENDING THE CASE AND WHERE APPLICABLE, UPON
              CONFIRMATION OF OWNERSHIP OF A FIDO DIDO NFT OR UPON RECEIPT OF
              THE CORRESPONDING PURCHASE PRICE.
            </p>

            <p>
              ALL SALES COMPLETED ON THE FIDO DIDO WEBSITE ARE FINAL. PURSUANT
              TO APPLICABLE LAW, YOU ACKNOWLEDGE THAT NO WITHDRAWAL, RETURN
              AND/OR REFUND RIGHTS APPLY.
            </p>

            <h2>4.3 NFT SECONDARY SALE ON THIRD-PARTY PLATFORM</h2>

            <p>
              USER MAY RESELL AND/OR PURCHASE FIDO DIDO NFT ON THIRD-PARTY
              PLATFORMS AS PART OF SECONDARY SALES.
            </p>

            <p>
              PLATFORMS DEDICATED TO SECONDARY SALES ARE THIRD-PARTY SERVICES
              THAT ARE NOT AFFILIATED WITH FIDO DIDO AND WHICH ACCESS AND USE
              ARE AT USER'S OWN RISK AND DISCRETION AND SUBJECT TO THEIR OWN
              APPLICABLE TERMS.
            </p>

            <p>
              FIDO DIDO MAY BENEFIT FROM A PERCENTAGE OF THE RESALE PRICE OF
              YOUR FIDO DIDO NFT, AS SET FORTH ON THE FIDO DIDO WEBSITE AND
              SUBJECT TO THE THIRD-PARTY PLATFORM'S POLICY ON WHICH THE RESALE
              IS COMPLETED.
            </p>

            <p>
              YOU UNDERTAKE TO ONLY RESELL AND/OR PURCHASE FIDO DIDO NFT ON
              THIRD-PARTY PLATFORMS THAT (I) CRYPTOGRAPHICALLY VERIFY EACH NFT
              OWNER'S RIGHTS TO DISPLAY AND LIST A FIDO DIDO NFT FOR SALE, TO
              ENSURE THAT ONLY THE ACTUAL OWNER OF THIS NFT CAN PROCEED WITH ITS
              RESALE, AND (II) PROVIDE FOR A PERCENTAGE OF THE RESALE PRICE TO
              BE AUTOMATICALLY GRANTED TO FIDODIO.IO UPON RESALE.
            </p>

            <p>
              BY RESELLING AND/OR PURCHASING A FIDO DIDO NFT ON AN AUTHORIZED
              THIRD-PARTY PLATFORM, YOU AGREE TO ABIDE BY THESE TERMS.
            </p>

            <h2>5. UNDERTAKINGS OF THE PARTIES</h2>

            <h3>5.1 USERS UNDERTAKINGS</h3>

            <p>
              USERS SHALL NOT, DIRECTLY OR INDIRECTLY, WITHOUT BEING EXPRESSLY
              AUTHORIZED BY THESE TERMS AND/OR THE DIGITAL OWNERSHIP ASSIGNMENT,
              OR BY PRIOR WRITTEN CONSENT OF FIDO DIDO, IN ANY WAY WHATSOEVER:
            </p>

            <ol>
              <li>
                COPY, MODIFY, COMMUNICATE, TRANSMIT OR CREATE ANY DERIVATIVE
                WORK, USE, COMMERCIALIZE OR REPRODUCE ALL OR PART OF THE FIDO
                DIDO WEBSITE AND/OR FIDO DIDO PROPERTY, AND RELATED INTELLECTUAL
                PROPERTY RIGHTS OF FIDO DIDO, OR REGISTER OR ATTEMPT TO REGISTER
                ANY TRADEMARK OR COPYRIGHT OR OTHERWISE ACQUIRE ADDITIONAL
                INTELLECTUAL PROPERTY RIGHTS IN OR TO ANY FIDO DIDO PROPERTY;
              </li>
              <li>
                USE THE FIDO DIDO WEBSITE OR ANY FIDODIO.IO PROPERTY TO CREATE,
                ENDORSE, SUPPORT, PROMOTE OR CONDONE ANY CONTENT, MATERIAL OR
                SPEECH THAT IS, OR MAY BE DEEMED TO BE BY FIDO DIDO AT ITS SOLE
                DISCRETION, DEFAMATORY, OBSCENE, PORNOGRAPHIC, INDECENT,
                ABUSIVE, OFFENSIVE, HARASSING, VIOLENT, HATEFUL, RACIST,
                DISCRIMINATORY, INFLAMMATORY OR OTHERWISE OBJECTIONABLE OR
                INAPPROPRIATE; AND, IN GENERAL, ACCESS, DOWNLOAD, UPLOAD, SHARE,
                COMMUNICATE ANY CONTENT AND/OR USE THE FIDO DIDO WEBSITE OR FIDO
                DIDO PROPERTY IN A WAY THAT MAY INFRINGE THE RIGHTS, INCLUDING
                INTELLECTUAL PROPERTY RIGHTS, OF FIDO DIDO OR THIRD PARTIES,
                DAMAGE THE REPUTATION, RIGHTS AND INTERESTS OF FIDODIO.IO, OR
                FALSELY SUGGEST AN AFFILIATION WITH OR ENDORSEMENT BY FIDO DIDO.
              </li>
              <li>
                DECOMPILE, DISASSEMBLE THE FIDODIO.IO WEBSITE, REVERSE ENGINEER
                OR ATTEMPT TO DISCOVER OR RECONSTRUCT THE SOURCE CODE, THE IDEAS
                ON WHICH IT IS BASED, THE ALGORITHMS, THE FILE FORMATS OR THE
                PROGRAMMING OR INTEROPERABILITY INTERFACES OF THE FIDO DIDO
                WEBSITE EXCEPT TO THE EXTENT PERMITTED BY LAW, IN ANY MANNER
                WHATSOEVER. IN THE EVENT THE USER WISHES TO OBTAIN THE
                INFORMATION NECESSARY TO IMPLEMENT THE INTEROPERABILITY OF FIDO
                DIDO THE WEBSITE WITH OTHER SOFTWARE DEVELOPED OR INDEPENDENTLY
                ACQUIRED BY THE USER, FOR USE IN ACCORDANCE WITH THE DESTINATION
                OF THE FIDO DIDO WEBSITE, THE USER UNDERTAKES, BEFORE RELYING ON
                A THIRD PARTY, TO FIRST CONSULT FIDO DIDO WHICH MAY PROVIDE THE
                NECESSARY INFORMATION FOR THE IMPLEMENTATION OF SUCH
                INTEROPERABILITY. THE USER ACKNOWLEDGE THAT, WHERE APPROPRIATE,
                THE EXACT COST INCURRED INTERNALLY BY FIDO DIDO FOR PROVIDING
                THIS INFORMATION WILL BE INVOICED BY FIDO DIDO TO THE USER;
              </li>
              <li>
                PROCEED ALONE, OR WITH HELP OF A THIRD-PARTY SERVICE PROVIDER,
                TO CORRECT OF ANY ERRORS IN AND/OR ALTER ANY CONTENT OF THE FIDO
                DIDO WEBSITE IN ORDER TO MAKE IT CONFORM TO HER/HIS OWN PURPOSES
                (FIDO DIDO ALONE RESERVES FOR ITSELF THE EXERCISE OF THIS RIGHT
                IN ACCORDANCE WITH EXCEPTIONS PROVIDED BY LAW); OR INTEGRATE OR
                COMBINE THE FIDO DIDO WEBSITE WITH OTHER SOFTWARE OR DOCUMENTS
                OR CREATE COMPOSITE OR DERIVATIVE WORKS WITH HELP OF ALL OR
                PARTS OF THE FIDO DIDO WEBSITE;
              </li>
              <li>
                VIOLATE ANY LAW OR REGULATION, OR MAKE ANY USE OF THE FIDO DIDO
                WEBSITE, SERVICES OR FIDO DIDO PROPERTY THAT MAY BE DEEMED
                CONTRARY TO PUBLIC ORDER OR UNFAIR.
              </li>
            </ol>

            <h3>5.2 UNDERTAKINGS OF FIDO DIDO</h3>

            <p>FIDO DIDO ENDEAVORS USE REASONABLE EFFORTS TO:</p>

            <ol>
              <li>ACT HONESTLY, FAIRLY AND PROFESSIONALLY,</li>
              <li>
                COMMUNICATE WITH THE HOLDERS OF FIDO DIDO NFT IN A FAIR AND
                CLEAR MANNER,
              </li>
              <li>
                PREVENT, IDENTIFY, MANAGE AND DISCLOSE ANY CONFLICTS OF INTEREST
                THAT MAY ARISE,
              </li>
              <li>
                MAINTAIN ALL OF ITS SYSTEMS AND SECURITY ACCESS PROTOCOLS TO
                APPROPRIATE STANDARDS OF APPLICABLE LAWS AND REGULATIONS, AND,
                IN GENERAL
              </li>
              <li>
                ACT IN THE BEST INTERESTS OF THE HOLDERS OF FIDO DIDO NFT AND
                TREAT THEM EQUALLY, UNLESS PROVIDED OTHERWISE ON THE FIDO DIDO
                WEBSITE OR ANY OTHER NOTICE BY FIDO DIDO.
              </li>
            </ol>

            <h2>6. SECURITY</h2>

            <h3>6.1 FIDO DIDO WEBSITE SECURITY</h3>

            <p>
              FIDO DIDO SHALL MAKE ITS BEST EFFORTS TO DEPLOY THE NECESSARY
              RESOURCES TO ENSURE USERS' ACCESS TO AND EFFECTIVE OPERATION OF
              THE FIDO DIDO WEBSITE TWENTY-FOUR HOURS A DAY AND SEVEN DAYS A
              WEEK. HOWEVER, GIVEN THE LIMITATIONS RELATED TO THE INTERNET, FIDO
              DIDO CANNOT GUARANTEE THAT ACCESS AND OPERATION OF THE FIDO DIDO
              WEBSITE WILL NOT BE INTERRUPTED, SUCH AS IN EVENT OF FORCE
              MAJEURE, MALFUNCTION OF THE USERS' EQUIPMENT, MALFUNCTIONS OF THE
              USERS' INTERNET NETWORKS AND/OR MAINTENANCE OPERATIONS DESIGNED TO
              IMPROVE THE FIDO DIDO WEBSITE.
            </p>

            <p>
              THE USER HEREBY REPRESENTS, WARRANTS, AND AGREES THAT, WHEN
              ACCESSING AND/OR USING THE FIDO DIDO WEBSITE AND SERVICES, THE
              USER SHALL REFRAIN FROM ANY ACT AND/OR OMISSION WHICH COULD, IN
              ANY WAY WHATSOEVER:
            </p>

            <ol>
              <li>JEOPARDIZE THE SECURITY OF THE FIDO DIDO WEBSITE;</li>
              <li>
                ATTEMPT, IN ANY MANNER, TO OBTAIN PASSWORDS OR OTHER SECURITY
                INFORMATION FROM ANY OTHER USER;
              </li>
              <li>
                VIOLATE THE SECURITY OF ANY COMPUTER NETWORK, OR CRACKS ANY
                PASSWORDS OR SECURITY ENCRYPTION CODES;
              </li>
              <li>
                RUN ANY PROCESSES THAT INTERFERE WITH THE PROPER WORKING OF THE
                FIDODIO.IO WEBSITE AND SERVICES;
              </li>
              <li>
                DISTURB, HINDER AND/OR PREVENT THE PROPER FUNCTIONING OF THE
                FIDO DIDO WEBSITE AND SERVICES (SUCH AS, BUT NOT LIMITED TO,
                DOWNLOADING VIRUSES OR MALICIOUS CODE WHATSOEVER OR BY
                PERFORMING HACKING ACTIVITIES OF ANY NATURE OR THAT OTHERWISE
                INTERFERE WITH THE PROPER FUNCTIONING OF THE FIDODIO.IO WEBSITE
                AND SERVICES).
              </li>
            </ol>

            <h3>6.2 MALICIOUS THIRD PARTIES</h3>

            <p>
              PLEASE BE AWARE THAT MALICIOUS THIRD PARTIES MAY OFFER FOR SALE
              NFT COUNTERFEITED FIDO DIDO PROPERTY AND/OR FALSELY ACT AS
              AFFILIATED TO OR ENDORSED BY FIDO DIDO. IN CASE OF DOUBT, PLEASE
              CONTACT FIDO DIDO IN ACCORDANCE WITH ARTICLE 12 BELOW.
            </p>

            <p>
              YOUR INTERACTIONS WITH THESE THIRD PARTIES ARE AT YOUR OWN RISKS
              AND DISCRETION. FIDO DIDO IS NOT RESPONSIBLE, IN ANY WAY
              WHATSOEVER, FOR ANY ACT OR OMISSION OF SAID MALICIOUS THIRD
              PARTIES, NOR ANY ADVERSE CONSEQUENCE RESULTING FROM YOUR
              INTERACTIONS WITH THEM.
            </p>

            <h2>7. DISCLAIMER</h2>

            <p>
              FIDO DIDO OFFERS SERVICES RELATED TO CRYPTO-ASSETS (NFT) THAT ARE
              UNIQUE AND NOT FUNGIBLE WITH OTHER CRYPTO-ASSETS. EACH FIDO DIDO
              NFT IS UNIQUE AND EXCLUSIVE TO ITS OWNER.
            </p>

            <p>
              FIDO DIDO IS NOT A PROVIDER OF DIGITAL ASSET SERVICES INCLUDING,
              BUT NOT LIMITED TO, SERVICES REGARDING INITIAL COIN OFFERING;
              CUSTODY OF DIGITAL ASSETS ON BEHALF OF THIRD PARTIES OR ACCESS TO
              DIGITAL ASSETS FOR THE PURPOSE OF HOLDING, STORING AND
              TRANSFERRING DIGITAL ASSETS; THE PURCHASE AND SALE OF DIGITAL
              ASSETS IN LEGAL TENDER; THE EXCHANGE OF DIGITAL ASSETS FOR OTHER
              DIGITAL ASSETS; THE OPERATION OF A DIGITAL ASSET TRADING PLATFORM;
              OR ANY SERVICES RELATED TO THIRD PARTY ORDER RECEPTION AND
              TRANSMISSION, THIRD PARTY PORTFOLIO MANAGEMENT, ADVICE,
              UNDERWRITING, GUARANTEED PLACEMENT AND UNGUARANTEED PLACEMENT.
            </p>

            <p>
              FIDO DIDO DOES NOT PROVIDE ASSET INTERMEDIATION SERVICES
              INCLUDING, BUT NOT LIMITED TO, SERVICES RELATED TO THE OFFER, TO
              CLIENTS OR POTENTIAL CLIENTS, TO ACQUIRE RIGHTS ON ONE OR MORE
              ASSETS ON THE BASIS OF THE POSSIBILITY OF A DIRECT OR INDIRECT
              FINANCIAL RETURN OR SIMILAR ECONOMIC EFFECT.
            </p>

            <p>
              IN THIS REGARD, THE USER HEREBY REPRESENTS, WARRANTS, AND AGREES
              THAT ANY USE OF THE FIDO DIDO WEBSITE AND SERVICES, INCLUDING ANY
              PURCHASE OF A FIDO DIDO NFT, IS MADE FOR ITS SOLE PERSONAL
              COLLECTION, USE AND ENJOYMENT. USER SHALL REFRAIN FROM ANY ACT
              AND/OR OMISSION WHICH COULD, IN ANY WAY WHATSOEVER, BE INTERPRETED
              AS OR SUGGEST THAT:
            </p>

            <ol>
              <li>
                THE USER IS ACCESSING OR USING THE FIDO DIDO WEBSITE AND/OR
                SERVICES, INCLUDING PURCHASING A FIDODIO.IO NFT, FOR SPECULATIVE
                OR INVESTMENT PURPOSES, FOR USE AS A SUBSTITUTE FOR CURRENCY OR
                OTHER MEDIUM OF EXCHANGE, OR FOR RESALE OR REDISTRIBUTION, OR
                THAT
              </li>
              <li>
                ACCESSING OR USING THE FIDO DIDO WEBSITE AND/OR SERVICES,
                INCLUDING PURCHASING A FIDO DIDO NFT, MAY CONSTITUTE AN
                OPPORTUNITY TO GAIN ECONOMIC BENEFIT OR PROFIT, OR AN
                INVESTMENT, EQUITY, OR OTHER OWNERSHIP OR PROFIT-SHARING
                INTEREST IN FIDO DIDO OR ITS AFFILIATES OR BUSINESS PARTNERS OF
                ANY KIND. IN THIS REGARD, FIDO DIDO MAKES NO WARRANTIES
                WHATSOEVER WITH REGARD TO ANY FUTURE VALUE OR RESALE PRICE OF A
                FIDO DIDO NFT.
              </li>
            </ol>

            <p>
              YOU ARE THE SOLE RESPONSIBLE FOR YOUR COMPLIANCE WITH APPLICABLE
              LAWS AND REGULATIONS, INCLUDING TAX OBLIGATIONS IN RELATION WITH
              NFT AND CRYPTOCURRENCIES. PLEASE BE AWARE THAT CHANGES IN
              APPLICABLE LAWS AND REGULATIONS MAY IMPACT THE SERVICES AND YOUR
              RIGHTS AND OBLIGATIONS REGARDING YOUR FIDO DIDO NFT.
            </p>

            <h2>8. WARRANTY AND LIABILITY</h2>

            <h3>8.1 WARRANTIES</h3>

            <p>
              IT IS EXPRESSLY AGREED THAT FIDO DIDO OBLIGATIONS UNDER THESE
              TERMS ARE OBLIGATIONS OF MEANS. TO THE GREATEST EXTENT PERMITTED
              BY APPLICABLE LAW, THE USER EXPRESSLY ACKNOWLEDGES THAT THE FIDO
              DIDO WEBSITE, SERVICES, INCLUDING FIDO DIDO NFT, ARE PROVIDED BY
              FIDO DIDO “AS IS”. OTHER THAN AS PROVIDED IN THESE TERMS AND TO
              THE FULLEST EXTENT PERMISSIBLE BY APPLICABLE LAW, FIDO DIDO MAKES
              NO OTHER WARRANTIES OR REPRESENTATIONS, EXPRESS OR IMPLIED, AND
              HEREBY DISCLAIMS ALL IMPLIED WARRANTIES.
            </p>

            <p>
              FIDO DIDO MAKES NO WARRANTIES WHATSOEVER, REGARDING THE FIDO DIDO
              WEBSITE, THE SERVICES, AND ANY TRANSACTION INVOLVING, IN WHOLE OR
              IN PART, FIDO DIDO NFT AND/OR CRYPTOCURRENCIES, INCLUDING, BUT NOT
              LIMITED TO, WITH REGARD TO ANY RISK ASSOCIATED WITH FIDO DIDO NFT,
              SUCH AS, RISK OF FAILURE TO TRANSFER THE NFT TO THE USER DUE TO AN
              ERROR, SUCH AS FORGOTTEN PASSWORDS, MISTYPED ADDRESSES OR
              INCORRECTLY CONSTRUCTED TRANSACTIONS, MINING ATTACKS,
              CYBERSECURITY ATTACKS, BLOCKCHAIN MALFUNCTIONS OR OTHER TECHNICAL
              ERRORS, TELECOMMUNICATIONS FAILURE, UNFAVORABLE REGULATORY
              DETERMINATIONS OR ACTIONS IN ONE OR MORE JURISDICTIONS (INCLUDING
              WITH RESPECT TO NFTS AND/OR CRYPTOCURRENCIES), TAXATION OF NFTS OR
              CRYPTOCURRENCIES, PERSONAL INFORMATION DISCLOSURE, UNINSURED
              LOSSES, UNANTICIPATED RISKS, VOLATILITY RISKS, SERVER FAILURE OR
              DATA LOSS, CORRUPTED OR OTHERWISE INACCESSIBLE DIGITAL WALLETS,
              UNAUTHORIZED ACCESS, INABILITY TO ACCESS, TRANSFER OR DISPLAY THE
              NFT, RISKS ARISING FROM THIRD-PARTY PROVIDERS, INCLUDING
              THIRD-PARTY PROVIDERS THAT MAY MINT AND/OR STORE THE NFT, AND ANY
              DAMAGES ARISING FROM ANY UNAUTHORIZED THIRD-PARTY ACTIVITIES,
              INCLUDING WITHOUT LIMITATION THE INTRODUCTION OF VIRUSES OR OTHER
              MALICIOUS CODE, PHISHING ATTACKS, SYBIL ATTACKS, FIFTY-ONE PERCENT
              (51%) ATTACKS, BRUTE FORCING CHANGES TO THE PROTOCOL RULES OF THE
              BLOCKCHAIN (I.E., “FORKS”), OR OTHER MEANS OF ATTACK THAT MAY
              AFFECT, IN ANY WAY, THE NFT.
            </p>

            <p>
              FIDO DIDO DOES NOT WARRANT THAT THE USER'S ACCESS AND USE OF THE
              FIDO DIDO WEBSITE AND THE SERVICES WILL BE UNINTERRUPTED, TIMELY
              AND FREE FROM ERRORS, MALFUNCTIONS, VIRUSES AND MALICIOUS CODES OF
              ANY KIND WHATSOEVER. NO INFORMATION PROVIDED ON THE FIDO DIDO
              WEBSITE IS EVER GUARANTEED IN ANY WAY WHATSOEVER.
            </p>

            <p>
              THE USER EXPRESSLY ACKNOWLEDGES AND ACCEPTS THAT ELECTRONIC
              COMMUNICATIONS MAY NOT BE FREE FROM INTERFERENCES WITH THIRD
              PARTIES. FIDO DIDO SHALL IN NO EVENT BE LIABLE FOR ANY DAMAGES,
              LOSSES, COSTS, EXPENSES AND LOSS OF PROFIT, OF WHATEVER NATURE AND
              KIND, RESULTING FROM OR ARISING OUT OF SUCH INTERFERENCE WITH
              THIRD PARTIES THROUGH THE INTERNET NETWORK.
            </p>

            <h3>8.2 INDEMNIFICATION</h3>

            <p>
              THE USER SHALL INDEMNIFY, DEFEND AND HOLD FIDO DIDO, AND ITS
              MEMBER, DIRECTORS, OFFICERS, EMPLOYEES, AND AGENTS (COLLECTIVELY,
              "THE FIDO DIDO CLAIMANTS") HARMLESS FROM AND AGAINST ANY AND ALL
              CLAIMS, LIABILITIES, JUDGMENTS, AWARDS, LOSSES, DAMAGES, COSTS AND
              EXPENSES (INCLUDING, BUT NOT LIMITED TO, REASONABLE ATTORNEYS'
              FEES), ARISING OUT FROM (I) ANY BREACH BY THE USER, OR ANY OF ITS
              RESPECTIVE EMPLOYEES OR AGENTS IF ANY, OF THIS TERMS OR OF ANY
              WARRANTY, REPRESENTATION, COVENANT OR OBLIGATION CONTAINED HEREIN;
              (II) ANY INFRINGEMENT OR ALLEGED INFRINGEMENT ON THE PART OF THE
              FIDO DIDO CLAIMANTS IN CONNECTION WITH ANY AND ALL USE OF THE FIDO
              DIDO WEBSITE, SERVICES AND/OR FIDODIO.IO NFT BY THE USER.
            </p>

            <h3>8.3 LIMITATION OF LIABILITY</h3>

            <p>
              TO THE GREATEST EXTENT PERMITTED BY APPLICABLE LAW, IN NO EVENT
              SHALL FIDO DIDO BE LIABLE FOR ANY INDIRECT DAMAGES CAUSED TO A
              USER IN RELATION TO ACCESS AND/OR USE OF THE FIDODIO.IO WEBSITE
              AND/OR THE SERVICES.
            </p>

            <h2>9. MISCELLANEOUS</h2>

            <h3>9.1 BREACH OF TERMS</h3>

            <p>
              IF THE USER'S UTILIZATION OF THE FIDO DIDO WEBSITE IS DEEMED IN
              BREACH OF THE TERMS, FIDO DIDO RESERVES THE RIGHT TO LIMIT,
              SUSPEND OR TERMINATE, TEMPORARILY OR PERMANENTLY, AS OF RIGHT,
              WITHOUT ANY INDEMNIFICATION, COMPENSATION OR REFUND WHATSOEVER
              BEING OWED AND WITHOUT ANY PREJUDICE TO ANY LEGAL ACTION THAT FIDO
              DIDO MAY BE ENTITLED TO, THE USER'S ACCESS TO THE FIDO DIDO
              WEBSITE AND/OR THE SERVICES AVAILABLE TO THE USER. FIDO DIDO SHALL
              INFORM THE USER OF ITS DECISION TO SUSPEND OR LIMIT THE USER'S
              RIGHTS AND MAY, AT ITS DISCRETION, DECIDE TO RESTORE THE USER'S
              RIGHTS.
            </p>

            <h3>9.2 THIRD PARTY CONTENT</h3>

            <p>
              THE FIDO DIDO WEBSITE MAY DISPLAY HYPERTEXT LINKS REDIRECTING THE
              USER TO THIRD PARTY WEBSITES AND/OR APPLICATIONS FIDO DIDO SHALL
              NOT BE HELD LIABLE, IN ANY WAY WHATSOEVER, IN RESPECT OF ANY
              HYPERTEXT LINKS TO THIRD PARTIES THAT MAY BE ACCESSIBLE ON THE
              FIDO DIDO WEBSITE. IN THIS RESPECT, PLEASE NOTE THAT FIDO DIDO
              NEITHER HAS ANY CONTROL OVER THE CONTENT PUBLISHED BY SUCH THIRD
              PARTIES NOR MONITORS SUCH CONTENT. AS A RESULT, FIDO DIDO SHALL IN
              NO EVENT BE HELD LIABLE IN RESPECT OF ANY CONTENT PUBLISHED BY
              THIRD PARTIES WHATSOEVER. THE USER IS HEREBY INVITED TO DULY READ
              THE TERMS AND CONDITIONS GOVERNING THIRD-PARTY WEBSITES AND
              APPLICATIONS THAT THE USER MAY ACCESS BY CLICKING ON HYPERTEXT
              LINKS DISPLAYED ON THE FIDO DIDO WEBSITE AND RELATED WEBSITE
              PAGES.
            </p>

            <p>
              IN THE EVENT THAT ANY CONTENT POSTED ON THE FIDO DIDO WEBSITE DOES
              NOT COMPLY WITH THESE TERMS AND/OR INFRINGES APPLICABLE LEGAL AND
              REGULATORY PROVISIONS, IN PARTICULAR BECAUSE IT CONSTITUTES
              MANIFESTLY UNLAWFUL CONTENT (E.G., DEFAMATORY, DENIGRATING OR
              INFRINGING ON THE USER'S INTELLECTUAL PROPERTY RIGHTS), ANY USER
              MAY REPORT SUCH INFRINGEMENT BY CONTACTING FIDODIO.IO IN
              ACCORDANCE WITH ARTICLE 12.
            </p>

            <h3>9.3 ASSIGNMENT</h3>

            <p>
              FIDO DIDO MAY TRANSFER ALL OR PART OF ITS RIGHTS AND OBLIGATIONS
              UNDER THESE TERMS TO ANY ENTITY, AFFILIATE, SUBSIDIARY OR
              THIRD-PARTY, INCLUDING, BUT NOT LIMITED TO, IN CASE OF MERGER,
              DIVISION, PARTIAL ASSET TRANSFER OR FULL OR PARTIAL BUSINESS
              DISPOSAL. THE USER SHALL NOT TRANSFER ALL OR PART OF ITS
              OBLIGATIONS UNDER THESE TERMS, IN ANY WAY WHATSOEVER, WITHOUT THE
              EXPRESS PRIOR WRITTEN AGREEMENT OF FIDO DIDO.
            </p>

            <h3>9.4 VALIDITY</h3>

            <p>
              IN THE EVENT ANY ONE OR MORE OF THE PROVISIONS OF THESE TERMS ARE
              UNENFORCEABLE, IT SHALL BE STRICKEN FROM THE APPLICABLE DOCUMENT,
              BUT THE REMAINDER OF THE TERMS SHALL REMAIN IN FORCE. THE
              PROVISIONS DECLARED UNENFORCEABLE SHALL BE REPLACED BY THE
              PROVISIONS THAT ARE CLOSEST IN MEANING AND SCOPE TO THE INITIAL
              PROVISIONS.
            </p>

            <h3>9.5 ELECTRONIC COMMUNICATION</h3>

            <p>
              IN ACCORDANCE WITH APPLICABLE LAW, THE USER ACKNOWLEDGES AND
              AGREES THAT INFORMATION EXCHANGED BETWEEN THE USER AND FIDO DIDO
              IN ELECTRONIC FORMAT (INCLUDING VIA EMAIL) SHALL BE DEEMED VALID
              MEANS OF COMMUNICATION, NOTICE AND PROOF, EQUIVALENT TO
              INFORMATION IN PAPER FORMAT.
            </p>

            <h2>10 APPLICABLE LAW</h2>

            <p>
              THE VALIDITY OF THESE TERMS AND ANY OF ITS TERMS AND PROVISIONS,
              AS WELL AS THE RIGHTS AND DUTIES OF THE PARTIES HEREUNDER, SHALL
              BE GOVERNED, INTERPRETED AND ENFORCED IN ACCORDANCE WITH THE
              FEDERAL LAW OF THE UNITED STATES AND THE LAW OF THE STATE OF
              DELAWARE.
            </p>

            <p>
              IN THE EVENT OF A DISPUTE ARISING BETWEEN THE PARTIES REGARDING
              THE INTERPRETATION, EXECUTION OR TERMINATION OF THESE TERMS, THE
              PARTIES SHALL ENDEAVOR TO RESOLVE SUCH ISSUE THROUGH AMICABLE
              MEANS. NOTWITHSTANDING ANYTHING TO THE CONTRARY PROVIDED HEREIN,
              THE STATE OR FEDERAL COURT OF APPROPRIATE JURISDICTION LOCATED IN
              KENT COUNTY, DELAWARE SHALL BE THE VENUE FOR ANY FORMAL DISPUTES
              BETWEEN USER AND FIDODIO.IO.
            </p>
            <h2>11 DIGITAL MILLENNIUM COPYRIGHT ACT NOTICE</h2>

            <p>
              WE RESPECT THE INTELLECTUAL PROPERTY RIGHTS OF OTHERS AND WE ASK
              YOU TO DO THE SAME. IF YOU ARE A COPYRIGHT OWNER OR AN AGENT OF A
              COPYRIGHT OWNER AND BELIEVE THAT ANY CONTENT ON THE SERVICES
              INFRINGES UPON YOUR COPYRIGHTS (OTHER THAN CONTENT THAT WAS
              PREVIOUSLY UPLOADED BY YOU TO FIDO DIDO AND AS TO WHICH THE
              USER-TO-USER COMPLAINT PROCESS APPLIES AS DESCRIBED BELOW), YOU
              MAY SUBMIT A NOTIFICATION PURSUANT TO THE DIGITAL MILLENNIUM
              COPYRIGHT ACT ("DMCA") BY CONTACTING OUR COPYRIGHT AGENT AT{" "}
              <span style={{color:"red"}}>[EMAIL PROTECTED]</span> OR TO THE
              ADDRESS PROVIDED IN ARTICLE 12, ATTENTION DMCA AGENT.
            </p>

            <p>
              IF A COPYRIGHT OWNER IS UNDER THE AGE OF 13, A DMCA NOTICE MUST BE
              SUBMITTED BY A PARENT OR OTHER REPRESENTATIVE OF THE RIGHTSHOLDER,
              RATHER THAN DIRECTLY BY AN UNDER-13 USER. YOU ACKNOWLEDGE THAT IF
              YOU FAIL TO COMPLY WITH ALL OF THE REQUIREMENTS OF THIS SECTION
              5(A), YOUR DMCA NOTICE MAY NOT BE VALID. YOU MUST PROVIDE THE
              FOLLOWING INFORMATION IN WRITING (SEE 17 U.S.C 512(C)(3) FOR
              FURTHER DETAIL):
            </p>

            <ul>
              <li>
                AN ELECTRONIC OR PHYSICAL SIGNATURE OF THE PERSON AUTHORIZED TO
                ACT ON BEHALF OF THE OWNER OF THE COPYRIGHT OR OTHER RIGHT BEING
                INFRINGED.
              </li>
              <li>
                A DESCRIPTION OF THE COPYRIGHT-PROTECTED WORK OR OTHER
                INTELLECTUAL PROPERTY RIGHT THAT YOU CLAIM HAS BEEN INFRINGED.
              </li>
              <li>
                A DESCRIPTION OF THE MATERIAL THAT YOU CLAIM IS INFRINGING AND
                WHERE IT IS LOCATED.
              </li>
              <li>YOUR ADDRESS, TELEPHONE NUMBER, AND EMAIL ADDRESS.</li>
              <li>
                A STATEMENT BY YOU THAT YOU HAVE A GOOD FAITH BELIEF THAT THE
                USE OF THOSE MATERIALS IS NOT AUTHORIZED BY THE COPYRIGHT OWNER,
                ITS AGENT, OR THE LAW.
              </li>
              <li>
                A STATEMENT BY YOU THAT THE ABOVE INFORMATION IN YOUR NOTICE IS
                ACCURATE AND THAT, UNDER PENALTY OF PERJURY, YOU ARE THE
                COPYRIGHT OR INTELLECTUAL PROPERTY OWNER OR AUTHORIZED TO ACT ON
                THE COPYRIGHT OR INTELLECTUAL PROPERTY OWNER'S BEHALF.
              </li>
            </ul>

            <h3>COUNTER-NOTICE</h3>

            <p>
              REGARDING ANY CONTENT THAT WAS REMOVED OR DISABLED, IF YOU BELIEVE
              THAT YOUR CONTENT IS NOT INFRINGING OR THAT YOU HAVE THE
              AUTHORIZATION FROM THE COPYRIGHT OWNER, THE COPYRIGHT OWNER'S
              AGENT, OR PURSUANT TO THE LAW, TO POST AND USE THE MATERIAL IN
              YOUR CONTENT, YOU MAY SEND A COUNTER-NOTICE TO OUR COPYRIGHT
              AGENT. ANY COUNTER-NOTICE SUBMITTED ON BEHALF OF AN UNDER-13 USER
              MUST BE SUBMITTED BY A PARENT OR OTHER ADULT REPRESENTATIVE. WHEN
              OUR COPYRIGHT AGENT RECEIVES A COUNTER-NOTICE, WE MAY SEND A COPY
              OF THE COUNTER-NOTICE TO THE ORIGINAL COMPLAINING PARTY INFORMING
              THAT PARTY THAT WE MAY, IN 10 BUSINESS DAYS, REPLACE THE REMOVED
              CONTENT OR STOP DISABLING IT. UNLESS THE COPYRIGHT OWNER FILES AN
              ACTION SEEKING A COURT ORDER AGAINST THE PROVIDER OF THE CONTENT,
              THE REMOVED CONTENT MAY BE REPLACED OR ACCESS TO IT RESTORED, IN
              10 TO 14 BUSINESS DAYS OR MORE AFTER RECEIPT OF THE
              COUNTER-NOTICE, IN FIDODIO.IO'S SOLE DISCRETION.
            </p>

            <h3>9.3 ASSIGNMENT</h3>

            <p>
              FIDO DIDO MAY TRANSFER ALL OR PART OF ITS RIGHTS AND OBLIGATIONS
              UNDER THESE TERMS TO ANY ENTITY, AFFILIATE, SUBSIDIARY OR
              THIRD-PARTY, INCLUDING, BUT NOT LIMITED TO, IN CASE OF MERGER,
              DIVISION, PARTIAL ASSET TRANSFER OR FULL OR PARTIAL BUSINESS
              DISPOSAL. THE USER SHALL NOT TRANSFER ALL OR PART OF ITS
              OBLIGATIONS UNDER THESE TERMS, IN ANY WAY WHATSOEVER, WITHOUT THE
              EXPRESS PRIOR WRITTEN AGREEMENT OF FIDO DIDO.
            </p>

            <h3>9.4 VALIDITY</h3>

            <p>
              IN THE EVENT ANY ONE OR MORE OF THE PROVISIONS OF THESE TERMS ARE
              UNENFORCEABLE, IT SHALL BE STRICKEN FROM THE APPLICABLE DOCUMENT,
              BUT THE REMAINDER OF THE TERMS SHALL REMAIN IN FORCE. THE
              PROVISIONS DECLARED UNENFORCEABLE SHALL BE REPLACED BY THE
              PROVISIONS THAT ARE CLOSEST IN MEANING AND SCOPE TO THE INITIAL
              PROVISIONS.
            </p>

            <h3>9.5 ELECTRONIC COMMUNICATION</h3>

            <p>
              IN ACCORDANCE WITH APPLICABLE LAW, THE USER ACKNOWLEDGES AND
              AGREES THAT INFORMATION EXCHANGED BETWEEN THE USER AND FIDO DIDO
              IN ELECTRONIC FORMAT (INCLUDING VIA EMAIL) SHALL BE DEEMED VALID
              MEANS OF COMMUNICATION, NOTICE AND PROOF, EQUIVALENT TO
              INFORMATION IN PAPER FORMAT.
            </p>

            <h2>10 APPLICABLE LAW</h2>

            <p>
              THE VALIDITY OF THESE TERMS AND ANY OF ITS TERMS AND PROVISIONS,
              AS WELL AS THE RIGHTS AND DUTIES OF THE PARTIES HEREUNDER, SHALL
              BE GOVERNED, INTERPRETED AND ENFORCED IN ACCORDANCE WITH THE
              FEDERAL LAW OF THE UNITED STATES AND THE LAW OF THE STATE OF
              DELAWARE.
            </p>

            <p>
              IN THE EVENT OF A DISPUTE ARISING BETWEEN THE PARTIES REGARDING
              THE INTERPRETATION, EXECUTION OR TERMINATION OF THESE TERMS, THE
              PARTIES SHALL ENDEAVOR TO RESOLVE SUCH ISSUE THROUGH AMICABLE
              MEANS. NOTWITHSTANDING ANYTHING TO THE CONTRARY PROVIDED HEREIN,
              THE STATE OR FEDERAL COURT OF APPROPRIATE JURISDICTION LOCATED IN
              KENT COUNTY, DELAWARE SHALL BE THE VENUE FOR ANY FORMAL DISPUTES
              BETWEEN USER AND FIDODIO.IO.
            </p>
          </div>
        </div>
      </center>
    </>
  );
}

export default TermsAndCondition