import React from "react";
import "./ip.css"

function IPRights() {
  return (
    <>
      <center>
        <div style={{ color: "white" }}>
          <h1 className = "heading" >
            {" "}
            INTELLECTUAL PROPERTY RIGHTS
          </h1>
          <h2> LAST UPDATED: JANUARY 2024 </h2>
          <h2>FIDOLABS IP RIGHTS-V.1</h2>{" "}
          <p className="small">
            <b>LAST UPDATED:</b> JANUARY 2024
          </p>{" "}
        </div>
        <div className="container">
          <div>
            <h2>1. DEFINITIONS</h2>{" "}
            <p>
              <span className="important">"ART"</span> REFERS TO ANY DIGITAL
              CREATION, ARTWORK, DESIGN, AND DRAWINGS ORIGINATED BY THE AUTHOR
              AND INITIALLY MADE AVAILABLE TO THE PUBLIC BY THE CREATOR. SUCH
              CREATIONS MAY BE LINKED TO A NON-FUNGIBLE TOKEN (NFT) CAPABLE OF
              TRANSFER OR LICENSING TO AN OWNER, SUBJECT TO THE RESTRICTIONS
              OUTLINED HEREIN.
            </p>{" "}
            <p>
              <span className="important">"CREATOR"</span> REFERS TO THE ENTITY
              THAT RELEASED THE PURCHASED NFT AND ASSOCIATED ART TO THE PUBLIC,
              ON BEHALF OF ITS AUTHOR, AND/OR ACQUIRED THE CORRESPONDING RIGHTS
              AND INTERESTS OF THOSE RIGHTS.{" "}
              <span className="important">FIDOLABS LLC</span>, WITH A REGISTERED
              ADDRESS OF [•], IS CONSIDERED THE CREATOR IN THIS CONTEXT.
            </p>{" "}
            <p>
              <span className="important">"NFT"</span> REFERS TO ANY
              NON-FUNGIBLE TOKEN (NFT) THAT IS BLOCKCHAIN-TRACKED, INCLUDING
              THOSE ADHERING TO THE{" "}
              <span className="important">ERC-721 STANDARD</span>, AND IS ISSUED
              AND TRADABLE ON A BLOCKCHAIN.
            </p>{" "}
            <p>
              <span className="important"> "EFFECTIVE DATE"</span> REFERS TO THE
              DATE WHEN THIS AGREEMENT BECOMES ATTACHED TO THE NFT FOR THE FIRST
              TIME IT IS RELEASED AND ACQUIRED, OR SUBSEQUENTLY ACQUIRED
              THEREAFTER, BY THE OWNER. THIS AGREEMENT SHALL BE DEEMED TO TAKE
              EFFECT ON THAT SPECIFIED DATE.
            </p>
            <p>
              <span className="important"> "OWNER"</span> REFERS TO THE CURRENT
              HOLDER OF THE NFT. IN THE EVENT OF A TRANSFER OF OWNERSHIP,
              INCLUDING THROUGH RESALE, THE RECIPIENT BECOMES THE EXCLUSIVE
              OWNER OF THE PURCHASED NFT. IT IS ACKNOWLEDGED THAT THERE MAY BE
              VARIOUS OWNERS OF EACH NFT OVER TIME, BUT AT ANY GIVEN MOMENT,
              ONLY ONE INDIVIDUAL SHALL BE RECOGNIZED AS THE OWNER. THE TERM
              "OWNER" ENCOMPASSES BOTH THE PRIMARY OWNER AND ANY SUBSEQUENT
              OWNERS.
            </p>
            <p>
              <span className="important">"OWN"</span> REFERS, IN THE CONTEXT OF
              AN NFT, THE POSSESSION OR RIGHTFUL ACQUISITION OF AN NFT THROUGH
              PURCHASE OR OTHER LEGITIMATE MEANS FROM AN AUTHORIZED SOURCE.
              OWNERSHIP IS CONFIRMED BY PROOF OF PURCHASE RECORDED ON THE
              RELEVANT BLOCKCHAIN, ESTABLISHING THE INDIVIDUAL AS THE LEGITIMATE
              OWNER OF THE ACQUIRED NFT.
            </p>
            <p>
              <span className="important">"PRIMARY ASSIGNMENT"</span> REFERS TO
              THE INITIAL TRANSFER BY THE CREATOR OF SPECIFIC RIGHTS, TITLE, AND
              INTERESTS RELATED TO THE ART TO THE PRIMARY OWNER, IN ACCORDANCE
              WITH THE TERMS OUTLINED IN ARTICLE 3 OF THIS AGREEMENT, AS DEFINED
              HEREINAFTER.
            </p>
            <p>
              <span className="important">"PRIMARY OWNER"</span> REFERS TO THE
              INDIVIDUAL OR ENTITY QUALIFYING AS THE OWNER ON THE EFFECTIVE DATE
              AND IS A PARTY TO THE PRIMARY ASSIGNMENT.
            </p>
            <p>
              <span className="important"> "PURCHASED NFT" </span>REFERS TO AN
              NFT THAT HAS BEEN ACQUIRED THROUGH PURCHASE OR ANY OTHER MEANS,
              ESTABLISHING OWNERSHIP BY THE INDIVIDUAL OR ENTITY.
            </p>
            <p>
              <span className="important"> "RESALE" </span> REFERS TO THE ACT OF
              THE OWNER SELLING THE PURCHASED NFT AND ASSOCIATED RIGHTS TO THE
              ART TO A SUBSEQUENT BUYER. THE SUBSEQUENT BUYER, UPON THE
              EFFECTIVE COMPLETION OF THE PURCHASE, SHALL THEN OWN THE PURCHASED
              NFT AND THE ASSOCIATED RIGHTS TO THE ART, TO THE EXTENT THAT SUCH
              RIGHTS WERE TRANSFERABLE UPON THE SALE, AND BECOME THE NEW OWNER
              THEREOF.
            </p>
            <p>
              <span className="important"> "SECONDARY ASSIGNMENT"</span> REFERS
              TO, IN THE EVENT OF A RESALE, ANY AND ALL ASSIGNMENTS BY THE OWNER
              OF ALL RIGHTS, TITLE, AND INTEREST IN AND TO THE INTELLECTUAL
              PROPERTY RIGHTS ASSOCIATED WITH THE ART (TO THE EXTENT ACTUALLY
              ASSIGNABLE) TO THE SUBSEQUENT BUYER OF THE PURCHASED NFT.
            </p>
            <h2>2. OBJECTIVE OF OWNERSHIP ASSIGNMENT AGREEMENT</h2>{" "}
            <p>
              THIS OWNERSHIP ASSIGNMENT AGREEMENT IS DESIGNED TO ESTABLISH THE
              TERMS AND CONDITIONS GOVERNING THE ASSIGNMENT OF RIGHTS, TITLE,
              AND INTEREST IN AND TO THE INTELLECTUAL PROPERTY RIGHTS ASSOCIATED
              WITH THE ART TO WHICH THIS AGREEMENT IS AFFIXED, HEREINAFTER
              REFERRED TO AS THE <span className="important">"AGREEMENT"</span>.
            </p>{" "}
            <p>
              THE AGREEMENT SHALL GOVERN THE PRIMARY ASSIGNMENT, WHEREIN THE
              CREATOR ASSIGNS SPECIFIC INTELLECTUAL PROPERTY RIGHTS ON THE ART
              TO THE PRIMARY OWNER. ADDITIONALLY, IT ENCOMPASSES ALL SECONDARY
              ASSIGNMENTS EXECUTED BETWEEN THE OWNER AND SUBSEQUENT BUYERS OF
              THE PURCHASED NFT, WHERE APPLICABLE.
            </p>
            <p>
              THIS AGREEMENT SHALL TAKE EFFECT AS OF THE EFFECTIVE DATE AND
              SHALL CONTINUE IN FORCE AS LONG AS IT REMAINS ATTACHED TO THE
              PURCHASED NFT. UPON ACQUIRING THE PURCHASED NFT AND RELATED ART
              THROUGH ANY MEANS WHATSOEVER (AS MENTIONED HEREIN). THE OWNER
              EXPRESSLY ACKNOWLEDGES HAVING READ THE CONTENTS OF THIS AGREEMENT
              AND AGREES TO ADHERE TO THE TERMS AND CONDITIONS OUTLINED HEREIN
              WITHOUT ANY VARIATIONS NOR AMENDMENTS WHATSOEVER.
            </p>
            <p>
              THIS AGREEMENT SHALL BE APPLICABLE TO THE PRIMARY ASSIGNMENT AND
              ALL SECONDARY ASSIGNMENTS, PROVIDED THAT NO OTHER WRITTEN
              AGREEMENT HAS BEEN EXECUTED BETWEEN THE PARTIES INVOLVED IN SUCH
              ASSIGNMENTS. IN THE EVENT OF A CONTRADICTION BETWEEN A SPECIFIC
              AGREEMENT AND A GENERAL AGREEMENT, THE PROVISIONS OF THE SPECIFIC
              AGREEMENT SHALL TAKE PRECEDENCE.
            </p>
            <p>
              FIDOLABS LLC RECOGNIZES THE DYNAMIC AND EVOLVING NATURE OF HOW
              INDIVIDUALS CREATE, UTILIZE, AND MONETIZE THEIR NFTS. THE PURPOSE
              OF THIS AGREEMENT HAS THE OBJECTIVE OF SAFEGUARDING THE HARD WORK
              AND CREATIVITY OF THE CREATORS WHILE GRANTING THE OWNERS THE
              FREEDOM AND FLEXIBILITY TO FULLY ENJOY THEIR PURCHASED NFTS AND
              RELATED ART ACCORDING TO THE AGREEMENT. FEEDBACK FROM OUR
              COMMUNITY ON THIS AGREEMENT IS WELCOMED, HOWEVER, ANY AMENDMENT
              HAS TO BE EXPRESSLY MENTIONED AND IN WRITING.
            </p>
            <h2>3. COMMUNITY ENGAGEMENT AND PROJECT PROMOTION</h2>
            <p>
              OUR SUCCESS IS INTERTWINED WITH THE PROSPERITY OF OUR COMMUNITY.
              WE ENCOURAGE SHARING WITH US YOUR MOMENTS WITH YOUR FIDO DIDO NFTS
              AND INVITE YOU TO SUBMIT PICTURES, ARTWORK, SCREENSHOTS, ETC., OF
              YOU, YOUR FRIENDS, AND FAMILY WITH YOUR FIDO DIDO NFT. IF YOU ARE
              AMENABLE TO US RESHARING THESE, KINDLY SUBMIT THEM HERE .
              <p>
                {" "}
                WE ARE ALSO KEEN TO LEARN ABOUT AND POTENTIALLY PROMOTE YOUR
                FIDO DIDO NFT PROJECTS, WHETHER THEY ARE FOR PERSONAL,
                NON-COMMERCIAL USE OR COMMERCIAL VENTURES. IF YOU ARE INITIATING
                A PROJECT INTENDED FOR COMMERCIAL USE (OF ANY BUDGET), PLEASE
                DESCRIBE IT HERE , ALLOWING US TO ENSURE ITS COMPLIANCE WITH
                THIS AGREEMENT. UPON APPROVAL, WE WILL DETERMINE HOW BEST TO
                SUPPORT YOUR ENDEAVOR.
              </p>
              <p>
                {" "}
                CONTACT US HERE AND VIA EMAIL AT [EMAIL ADDRESS] TO INITIATE A
                DISCUSSION ABOUT ENTERING INTO A SPECIFIC AGREEMENT. AS THE
                CREATOR, WE RESERVE THE RIGHT TO AUDIT AND MAINTAIN AUTHORITY,
                EXERCISING SOLE DISCRETION IN GRANTING OR DENYING OTHER
                AGREEMENTS OR AUTHORIZATION TO USE THE ART.
              </p>
            </p>
            <h2>4. ASSIGNMENT & LIMITED LICENSE TO USE</h2>
            <h3>PERSONAL USE</h3>
            <p>
              IN CONSIDERATION OF THE PURCHASE PRICE, AS DEFINED HEREINAFTER,
              AND SUBJECT TO THE PRIMARY OWNER'S ONGOING COMPLIANCE WITH THE
              TERMS OF THIS AGREEMENT AND ALL APPLICABLE LAWS, THE CREATOR
              HEREBY GRANTS A LIMITED, WORLDWIDE, NONEXCLUSIVE LICENSE TO THE
              PRIMARY OWNER. THIS LICENSE ALLOWS THE PRIMARY OWNER TO COPY,
              ACCESS, AND USE THEIR FIDO DIDO NFT AND RELATED ART SOLELY FOR
              THEIR PERSONAL, NON-COMMERCIAL USE[1]. IT IS UNDERSTOOD THAT THE
              PRIMARY OWNER MUST MAINTAIN ALL COPYRIGHT AND OTHER PROPRIETARY
              NOTICES INTACT.
            </p>
            <h3>COMMERCIAL USE</h3>
            <p>
              THE PRIMARY OWNER IS GRANTED A LIMITED, WORLDWIDE, NONEXCLUSIVE
              LICENSE TO COPY, ACCESS, USE, AND OTHERWISE EXPLOIT THEIR FIDO
              DIDO NFT AND RELATED ART. THIS IS FOR THE PURPOSE OF
              COMMERCIALIZING AND PROMOTING THIRD-PARTY GOODS AND SERVICES IN A
              MANNER THAT INCORPORATES, CONTAINS, OR CONSISTS OF THE GRAPHICAL
              IMAGE OF THE PRIMARY OWNER'S FIDO DIDO NFT. THIS COMMERCIAL USE
              WILL BE ALLOWED BY AN EXPRESS PERMISSION BY THE CREATOR REGARDLESS
              OF THE PROJECT'S VALUE[2].
            </p>
            <p>
              THIS LIMITED LICENSE FOR COMMERCIAL USE IS SUBJECT TO THE
              FOLLOWING CONDITIONS:
            </p>
            <ul>
              <li>
                THE PRIMARY OWNER DOES NOT HAVE ANY RIGHT TO MODIFY OR PRESENT
                ITS FIDO DIDO NFT OR RELATED ART IN ANY WAY OR ANY CONTEXT THAT
                DEPICTS HATRED, INTOLERANCE, VIOLENCE, CRUELTY, OR ANYTHING ELSE
                THAT COULD REASONABLY BE FOUND TO CONSTITUTE HATE SPEECH, BE
                OFFENSIVE, DEMEANING, NOT COMPORT WITH THE INCLUSIVE VALUES OF
                THE FIDO DIDO BRAND AND COMMUNITY, OR OTHERWISE INFRINGE UPON
                THE RIGHTS OF OTHERS OR THE FIDO DIDO COMMUNITY.
              </li>

              <li>
                THE PRIMARY OWNER MAY NOT USE AND/OR SUBLICENSE THEIR FIDO DIDO
                NFT OR RELATED ART TO PROMOTE, ADVERTISE, MARKET, OR SELL ANY
                THIRD-PARTY GOODS OR SERVICES WITHOUT SUCH USE AND/OR SUBLICENSE
                BEING EXPRESSLY APPROVED BY THE CREATOR.
              </li>

              <li>
                THE PRIMARY OWNER MAY NOT USE THE NAME "FIDO DIDO" OR ANY FIDO
                DIDO NAME, LOGO, OR TRADEMARK, THE NAME OF ANY FIDO DIDO
                CHARACTERS (AS APPLICABLE), OR ANY ANIMATION, CHARACTERS,
                THEMES, OR OTHER MATERIAL RELATED TO THE CREATOR'S OWN DIGITAL
                CONTENT.
              </li>

              <li>
                THE PRIMARY OWNER MAY NOT COMBINE ITS FIDO DIDO NFT WITH ANY
                OTHER FIDO DIDO OR MODIFIED FIDO DIDO THAT IT DOES NOT OWN,
                EXCEPT ON EXPLICIT PERMISSION OF THE OTHER FIDO DIDO NFT OWNER.
              </li>

              <li>
                THE PRIMARY OWNER MAY NOT ATTEMPT TO TRADEMARK, COPYRIGHT, OR
                OTHERWISE ACQUIRE ADDITIONAL INTELLECTUAL PROPERTY RIGHTS IN OR
                TO "FIDO DIDO" OR ANY FIDO DIDO NFT OR RELATED ART OR CONTENT.
              </li>
            </ul>
            <h2>5. WARRANTIES AND INDEMNIFICATION</h2>
            <p>
              IN THE EVENT THAT A PRIMARY OWNER UTILIZES THE LIMITED, WORLDWIDE,
              NONEXCLUSIVE LICENSE TO COPY, ACCESS, USE, AND OTHERWISE EXPLOIT
              THEIR FIDO DIDO NFT AND RELATED ART FOR THEIR OWN COMMERCIAL
              PURPOSES, AS ALLOWED BY THIS AGREEMENT, THE PRIMARY OWNER
              REPRESENTS AND WARRANTS THAT THEY WILL TAKE ALL NECESSARY STEPS TO
              CONDUCT THEIR COMMERCIAL ACTIVITIES IN A LEGAL MANNER. THIS
              INCLUDES, BUT IS NOT LIMITED TO, FORMING ANY NEEDED CORPORATE
              ENTITY, BECOMING DULY ORGANIZED, VALIDLY EXISTING, AND DULY
              QUALIFIED TO DO BUSINESS IN ALL JURISDICTIONS WHERE THOSE
              ACTIVITIES ARE CARRIED OUT. THE PRIMARY OWNER SHALL ALSO REMAIN IN
              GOOD STANDING UNDER AND ABIDE BY ALL APPLICABLE LAWS, RULES, AND
              REGULATIONS RELATED TO THOSE ACTIVITIES.
            </p>
            <p>
              FURTHERMORE, THE PRIMARY OWNER REPRESENTS AND WARRANTS THAT THEY
              POSSESS THE REQUISITE POWER AND AUTHORITY TO CARRY OUT THEIR
              COMMERCIAL ACTIVITIES. THIS ENCOMPASSES HAVING SUFFICIENT
              INSURANCE (
              <span className="important">
                OR AS EXPRESSLY REQUESTED BY THE CREATOR
              </span>
              ) TO ENSURE THEY CAN MEET THEIR OBLIGATIONS TO THEIR CUSTOMERS AND
              INDEMNIFICATION OBLIGATIONS TO THE CREATORS.
            </p>
            <p>
              IN THE EVENT THAT A PRIMARY OWNER UTILIZES THE LIMITED, WORLDWIDE,
              NONEXCLUSIVE LICENSE TO COPY, ACCESS, USE, AND OTHERWISE EXPLOIT
              THEIR FIDO DIDO NFT AND RELATED ART BY GRANTING A SUBLICENSE
              AND/OR ALLOWING THIRD PARTIES TO USE THEIR FIDO DIDO NFT, AS
              ALLOWED FOR BY THIS AGREEMENT, THE PRIMARY OWNER REPRESENTS AND
              WARRANTS THAT THEY WILL TAKE ALL NECESSARY STEPS TO ENSURE THAT
              THE THIRD PARTY IS CONDUCTING THEIR COMMERCIAL ACTIVITIES IN A
              LEGAL MANNER. THIS INCLUDES, BUT IS NOT LIMITED TO, FORMING ANY
              NEEDED CORPORATE ENTITY, BECOMING DULY ORGANIZED, VALIDLY
              EXISTING, AND DULY QUALIFIED TO DO BUSINESS IN ALL JURISDICTIONS
              WHERE THOSE ACTIVITIES ARE CARRIED OUT. THE PRIMARY OWNER SHALL
              ALSO ENSURE THAT THE THIRD PARTY REMAINS IN GOOD STANDING UNDER
              AND ABIDES BY ALL APPLICABLE LAWS, RULES, AND REGULATIONS RELATED
              TO THOSE ACTIVITIES. FURTHERMORE, THE PRIMARY OWNER REPRESENTS AND
              WARRANTS THAT THEY POSSESS THE REQUISITE POWER AND AUTHORITY TO
              CARRY OUT THEIR COMMERCIAL ACTIVITIES. THIS ENCOMPASSES HAVING
              SUFFICIENT INSURANCE TO ENSURE THEY CAN MEET THEIR OBLIGATIONS TO
              THEIR CUSTOMERS AND INDEMNIFICATION OBLIGATIONS TO THE CREATORS.
            </p>
            <p>
              THE PRIMARY OWNER (THE "
              <span className="important">INDEMNIFYING PARTY</span>") SHALL
              INDEMNIFY, DEFEND, AND HOLD HARMLESS THE CREATOR FROM AND AGAINST
              ANY LOSSES, DAMAGES, CLAIMS, ACTIONS, DEMANDS, JUDGMENTS,
              LIABILITY, AND/OR SUITS, INCLUDING REASONABLE ATTORNEY'S FEES, AS
              INCURRED. THESE MAY BE ASSERTED BY ANY PERSONS OR ENTITIES ARISING
              OUT OF OR RELATED TO THE PRIMARY OWNER'S USE AND/OR SUBLICENSING
              OF THE FIDO DIDO NFT AND RELATED ART FOR COMMERCIAL PURPOSES (AS
              PERMITTED IN THIS AGREEMENT). THIS INDEMNIFICATION ALSO EXTENDS TO
              ANY BREACH OF THE INDEMNIFYING PARTY'S WARRANTIES AND
              REPRESENTATIONS AS OUTLINED IN THIS AGREEMENT.
            </p>
            <h2>6. TERMINATION OF LIMITED LICENSE</h2>
            <p>
              THE AFOREMENTIONED LIMITED LICENSES APPLY EXCLUSIVELY DURING THE
              PERIOD THAT THE PRIMARY OWNER OWNS THE FIDO DIDO NFT ASSOCIATED
              WITH ITS FIDO DIDO. THESE LICENSES TERMINATE EFFECTIVE IMMEDIATELY
              AT THE POINT WHEN THE PRIMARY OWNER NO LONGER OWNS ITS FIDO DIDO
              NFT WITHOUT THE NEED OF ANY OTHER NOTICE NOR FORMALITY WHATSOEVER.
            </p>
            <p>
              FURTHERMORE, IF THE SCOPE OF THE LICENSES GRANTED IN SECTIONS 3
              AND 4 HEREIN IS EXCEEDED WITHOUT ENTERING INTO A SEPARATE AND
              SPECIFIC AGREEMENT OR PERMISSION, YOU ACKNOWLEDGE AND AGREE THAT:
              (I) YOU ARE IN BREACH OF THIS LICENSE, (II) IN ADDITION TO ANY
              REMEDIES THAT MAY BE AVAILABLE TO THE CREATOR AT LAW OR IN EQUITY,
              THE CREATOR MAY IMMEDIATELY TERMINATE THIS LICENSE WITHOUT THE
              REQUIREMENT OF NOTICE, AND (III) YOU WILL BE RESPONSIBLE TO
              REIMBURSE THE CREATOR FOR ANY FEES, COSTS, AND EXPENSES INCURRED
              BY THE CREATOR DURING THE COURSE OF ENFORCING THE TERMS OF THIS
              LICENSE AGAINST YOU. THIS INCLUDES BUT IS NOT LIMITED TO
              ACCOUNTING AND LEGAL FEES, COSTS, AND EXPENSES.
            </p>
            <h2>7. OWNERSHIP RIGHTS</h2>
            <p>
              THE PURCHASE OF A FIDO DIDO NFT MEANS THAT THE PRIMARY OWNER HAS
              FULL OWNERSHIP RIGHTS IN THE FIDO DIDO NFT, INCLUDING THE RIGHT TO
              STORE, SELL, AND TRANSFER THE NFT. HOWEVER, THE PRIMARY OWNER
              EXPRESSLY ACKNOWLEDGES AND AGREES THAT THIS PURCHASE OF THE FIDO
              DIDO NFT DOES NOT GRANT ANY RIGHTS, WHETHER EXPRESS OR IMPLIED, IN
              (INCLUDING, WITHOUT LIMITATION, ANY COPYRIGHTS AND/OR OTHER
              INTELLECTUAL PROPERTY RIGHTS IN OR TO) THE FIDO DIDO ASSOCIATED
              WITH THE NFT OTHER THAN THE LIMITED LICENSES GRANTED IN SECTION 3
              AND 4 ABOVE.
            </p>
            <p>
              THE PRIMARY OWNER'S RIGHTS AND INTEREST IN ITS FIDO DIDO NFT, ITS
              ASSOCIATED FIDO DIDO, ANY DERIVATIVE FIDO DIDO, AND ANY ART
              PROVIDED BY THESE TERMS WILL IMMEDIATELY TERMINATE UPON ANY
              SUBSEQUENT SALE, TRANSFER, DISPOSSESSION, BURNING, OR ANY OTHER
              FORM OF RELINQUISHMENT OF OWNERSHIP WITHOUT THE NEED OF ANY OTHER
              NOTICE OR FORMALITY.{" "}
            </p>
            <p>
              ANY USE OF THE ART OTHER THAN AS EXPRESSLY AUTHORIZED HEREIN,
              WITHOUT THE PRIOR EXPLICIT WRITTEN PERMISSION OF THE CREATOR, IS
              STRICTLY PROHIBITED. SUCH UNAUTHORIZED USE SHALL IMMEDIATELY
              TERMINATE THE RIGHT TO ACCESS AND USE THE FIDO DIDO NFT WEBSITE
              (AS DEFINED IN FIDO DIDO NFT TERMS OF SERVICE) AND ALL RIGHTS AND
              LICENSES GRANTED BY THESE TERMS. ADDITIONALLY, SUCH UNAUTHORIZED
              USE MAY VIOLATE APPLICABLE LAWS, INCLUDING COPYRIGHT AND TRADEMARK
              LAWS, AND APPLICABLE COMMUNICATIONS REGULATIONS AND STATUTES.
            </p>
            <p>
              NOTHING IN THIS AGREEMENT SHALL BE INTERPRETED IN ANYWAY AS
              GRANTING ANY LICENSE OF INTELLECTUAL PROPERTY RIGHTS TO YOU OTHER
              THAN AS EXPLICITLY SET FORTH IN THIS AGREEMENT.
            </p>
            <h2>8. SECONDARY ASSIGNMENT</h2>
            <p>
              THE PRIMARY OWNER AND, WHERE APPLICABLE, ALL SUBSEQUENT OWNERS,
              SHALL HAVE THE RIGHT TO RESELL THE PURCHASED FIDO DIDO NFT
              ("RESALE"), AND RELATED ART, ON A MARKETPLACE THAT ALLOWS THE
              PURCHASE AND SALE OF NFTS. THE OWNER SHALL PROVIDE ITS BEST
              EFFORTS TO RESELL THE PURCHASED NFT ON A MARKETPLACE WHICH: (I)
              CRYPTOGRAPHICALLY VERIFIES EACH NFT OWNER'S RIGHTS TO DISPLAY THE
              ART TO ENSURE THAT ONLY THE ACTUAL OWNER CAN DISPLAY THE ART FOR
              RESALE, AND (II) PROVIDES FOR A PERCENTAGE OF THE RESALE PRICE TO
              BE AUTOMATICALLY GRANTED TO THE CREATOR UPON RESALE.
            </p>
            <p>
              ANY SUBSEQUENT OWNER OR OWNER(S) SHALL POSSESS THE RIGHT TO
              LICENSE, ASSIGN, OR OTHERWISE TRANSFER ALL OR PART OF THE
              INTELLECTUAL PROPERTY RIGHTS GRANTED BY THIS AGREEMENT TO A THIRD
              PARTY IN ACCORDANCE WITH THE TERMS MENTIONED HEREIN.
            </p>
            <p>
              IN THE EVENT OF A TRANSFER OF OWNERSHIP OF THE PURCHASED FIDO DIDO
              NFT, IN ANY MANNER, INCLUDING RESALE, THE OWNER AGREES TO ASSIGN
              TO THE SUBSEQUENT BUYER OF THE PURCHASED NFT ALL RIGHTS ON THE
              RELATED ART DETAILED IN ARTICLE 3 OF THIS AGREEMENT. THIS
              ASSIGNMENT SHALL BE MADE UNDER THE SAME CONDITIONS, TO THE EXTENT
              SUCH RIGHTS HAVE NOT BEEN PREVIOUSLY TRANSFERRED TO A THIRD PARTY
              IN COMPLIANCE WITH THE TERMS OUTLINED IN THIS AGREEMENT.
            </p>
            <p>
              THIS AGREEMENT SHALL GOVERN ANY RESALE ATTACHED TO THE PURCHASED
              FIDO DIDO NFT, PROVIDED THAT NO OTHER AGREEMENT HAS BEEN CONCLUDED
              BETWEEN THE OWNER AND THE SUBSEQUENT BUYER. ANY SUCH ADDITIONAL
              AGREEMENT SHALL APPLY EXCLUSIVELY BETWEEN THE PARTIES INVOLVED IN
              SAID AGREEMENT.
            </p>
            <h2>9. COMPENSATION</h2>
            <p>
              IT IS EXPLICITLY AGREED THAT THE GRANT OF ALL INTELLECTUAL
              PROPERTY RIGHTS WHETHER TO THE PRIMARY OWNER UNDER THE PRIMARY
              ASSIGNMENT OR TO SUBSEQUENT OWNERS THROUGH A SECONDARY ASSIGNMENT
              IS MADE IN CONSIDERATION OF THE PRICE PAID BY THE OWNER TO ACQUIRE
              THE FIDO DIDO NFT, AS INDICATED ON THE NFT MARKETPLACE OF
              ACQUISITION (THE "PURCHASE PRICE"), WHERE APPLICABLE, AND IS
              HEREBY DEEMED FIXED AND DEFINITIVE.
            </p>
            <p>
              NOTWITHSTANDING THE ABOVE, THE CREATOR SHALL ALSO BE ENTITLED TO
              COMPENSATION FOR ANY RESALE OF THE COMPLETE WORK. THIS
              COMPENSATION SHALL BE DETERMINED BASED ON THE PERCENTAGE OF
              COMMISSION SET BY THE NFT MARKETPLACE WHERE THE RESALE IS
              CONCLUDED.
            </p>
            <h2>10. MORAL RIGHTS</h2>
            <p>
              THE CREATOR SHALL POSSESS THE RIGHT TO ENFORCE, ON BEHALF OF THE
              AUTHOR, ALL MORAL RIGHTS OF THE AUTHOR OF THE ART, AS PROVIDED BY
              APPLICABLE LAW, WHICH SHALL REMAIN PERPETUAL, INALIENABLE,
              IMPRESCRIPTIBLE, AND, IN GENERAL, ABSOLUTE.
            </p>
            <p>
              THE OWNER HEREBY COMMITS TO COMPLY, AND TO ENSURE THAT ITS
              CONTRACTORS, INCLUDING LICENSEES, SUBLICENSEES, SUBSEQUENT BUYERS,
              AND THIRD PARTIES, COMPLY WITH THE AUTHOR'S MORAL RIGHTS IN ANY
              AND ALL USE OF THE ART. THIS INCLUDES, IN PARTICULAR, THE
              FOLLOWING RIGHTS:
            </p>
            <p>
              (I) RIGHT OF AUTHORSHIP: THIS ENTITLES THE CREATOR TO DEMAND AND
              CLAIM AT ANY TIME THAT THE AUTHOR'S CHOSEN NAME BE MENTIONED ON
              ANY MODE OF PUBLICATION OF THE ART.
            </p>
            <p>
              (II) RIGHT TO PRESERVE THE INTEGRITY OF THE ART: THIS ENTITLES THE
              CREATOR TO OPPOSE ANY MODIFICATION, DELETION, OR ADDITION LIKELY
              TO ALTER THE ART OR ANY USE OF THE ART THAT MAY ALTER ITS SPIRIT,
              DEVALUE IT, OR OTHERWISE BE DEEMED PREJUDICIAL TO THE REPUTATION
              OF THE CREATOR OR THE FIDO DIDO BRAND OR COMMUNITY.
            </p>
            <h2>11. TRADEMARKS AND PROMOTION</h2>
            <p>
              WHEN USING THE FIDO DIDO NFTS AND RELATED ART, IN ANY MANNER,
              INCLUDING BUT NOT LIMITED TO ITS PUBLICATION, EXPLOITATION, AND/OR
              PROMOTION, THE OWNER SHALL REFRAIN FROM USING THE TRADEMARKS,
              SERVICE MARKS, OR PROPRIETARY WORDS OR SYMBOLS OF THE CREATOR.
              THIS RESTRICTION APPLIES UNLESS OTHERWISE PERMITTED BY WRITTEN
              AGREEMENT WITH THE CREATOR.
            </p>
            <p>
              BY EXCEPTION, WHEN USING THE ART FOR NON-COMMERCIAL PURPOSES ONLY,
              THE OWNER SHALL HAVE THE RIGHT TO REFERENCE THE CREATOR BY USING
              THE DENOMINATION "FIDO DIDO NFT" OR OTHER DENOMINATIONS THAT THE
              CREATOR MAY DIRECT FROM TIME TO TIME UNLESS INFORMED OTHERWISE BY
              THE CREATOR. THE OWNER SHALL TAKE CARE THAT SUCH USE SHALL NOT, IN
              ANY WAY WHATSOEVER, DAMAGE OR ADVERSELY IMPACT THE CREATOR’S
              REPUTATION, THE FIDO DIDO BRAND, OR COMMUNITY.
            </p>
            <p>
              THE CREATOR SHALL HAVE THE RIGHT, BUT NOT THE OBLIGATION, AT ITS
              SOLE DISCRETION, TO PROMOTE, INCLUDING THROUGH SOCIAL MEDIA, ANY
              PUBLIC USE OF THE FIDO DIDO NFTS AND RELATED ART BY THE OWNER,
              UNLESS THE OWNER INFORMS THE CREATOR OTHERWISE. THE OWNER SHALL
              NOT USE THE ART IN A WAY THAT WOULD OR COULD PRESENT THE CREATOR
              AS ENDORSING, RECOMMENDING, OR FAVORING, IN ANY WAY WHATSOEVER,
              THE OWNER AND/OR ITS USE OF THE ART WITHOUT THE CONSENT AND
              PERMISSION OF THE CREATOR.
            </p>
            <p>
              THE TRADEMARKS, SERVICE MARKS, TRADE NAMES, AND LOGOS, INCLUDING
              FIDO DIDO, AND ANY THIRD-PARTY MARKS USED AND DISPLAYED THROUGH
              ANY SERVICE ARE TRADEMARKS OF THE CREATOR, ITS LICENSORS,
              AFFILIATES, OR SPONSORS, AND MAY NOT BE USED BY A PRIMARY OWNER
              OTHER THAN TO FACTUALLY DESCRIBE ITS FIDO DIDO NFT OR FIDO DIDO
              ENHANCEMENT WHEN LISTING IT FOR SALE OR DISTRIBUTION OR FOR
              NON-COMMERCIAL PURPOSES. THE CREATOR RETAINS THE RIGHT TO MONITOR
              AND POLICE THE USE OF TRADEMARKS, INCLUDING BUT NOT LIMITED TO:
              (A) TAKE ALL REASONABLE MEASURES, INCLUDING WITHOUT LIMITATIONS
              BRINGING CIVIL ACTIONS FOR TRADEMARK INFRINGEMENT, TO STOP THE USE
              OF MARKS WHICH, IN OUR SOLE JUDGMENT, ARE THE SAME AS OR
              CONFUSINGLY SIMILAR TO OUR TRADEMARKS, AND (B) TAKE ALL REASONABLE
              MEASURES, INCLUDING WITHOUT LIMITATIONS BRINGING PROCEEDINGS IN
              THE UNITED STATES PATENT AND TRADEMARK OFFICE OR ELSEWHERE, TO
              PREVENT THE REGISTRATION OF MARKS WHICH, IN OUR SOLE JUDGMENT, ARE
              THE SAME AS OR CONFUSINGLY SIMILAR TO THE TRADEMARKS.
            </p>
            <h2>12. MUTUAL GOOD FAITH COOPERATION</h2>
            <p>
              THE CREATOR AND THE OWNER SHALL – AT ALL TIMES – COLLABORATE IN
              GOOD FAITH AND PROVIDE REASONABLE ASSISTANCE TO EACH OTHER IN
              LEGAL PROCEEDINGS RELATED TO THE FIDO DIDO NFT OR ANY DERIVATIVE
              WORKS, INCLUDING ANY LEGAL ACT (OR OTHERWISE AS DEEMED APPROPRIATE
              BY THE CREATOR) AIMED AT SAFEGUARDING ANY INFRINGEMENT OF THE
              INTELLECTUAL PROPERTY RIGHTS ASSOCIATED WITH FIDO DIDO.
            </p>
            <p>
              IN THE EVENT OF THE OWNER'S INACTION UPON WRITTEN NOTICE BY THE
              CREATOR, THE CREATOR RETAINS THE RIGHT TO SAFEGUARD AND UPHOLD THE
              RIGHTS LINKED THE FIDO DIDO, WHICH MAY INCLUDE LEGAL ACTIONS.
            </p>
            <h2>13. GOVERNING LAW</h2>
            <p>
              IF ANY PROVISION IN THIS AGREEMENT IS DEEMED ILLEGAL, INVALID, OR
              UNENFORCEABLE, WHETHER IN WHOLE OR IN PART, THE PROVISION SHALL BE
              APPLIED WITH NECESSARY DELETIONS OR MODIFICATIONS TO MAKE IT
              LEGAL, VALID, AND ENFORCEABLE, PRESERVING THE INITIAL INTENT OF
              THE PARTIES.
            </p>
            <p>
              THE VALIDITY OF THIS AGREEMENT, ITS TERMS, AND PROVISIONS, AS WELL
              AS THE RIGHTS AND DUTIES OF THE PARTIES, SHALL BE GOVERNED,
              INTERPRETED, AND ENFORCED IN ACCORDANCE WITH THE LAWS OF THE
              UNITED STATES OF AMERICA FOR FEDERAL LAW MATTERS AND THE STATE OF
              DELAWARE FOR STATE LAW MATTERS.
            </p>
          </div>
        </div>
      </center>
    </>
  );
}

export default IPRights;
