import React from 'react'

function index() {
  return (
    <>
      <center>
        {" "}
        <div className="container-rights">
          <h2 style={{ fontSize: "30px", textAlign: "center" }}>
            PRIVACY POLICY
          </h2>
          <p>
            WELCOME TO FIDO DIDO! THIS PRIVACY POLICY OUTLINES HOW WE COLLECT,
            USE, AND SHARE YOUR PERSONAL INFORMATION WHEN YOU VISIT OR MAKE A
            PURCHASE THROUGH OUR WEBSITE,{" "}
            <span className="important">WWW.FIDODIDO.IO</span> (REFERRED TO AS
            THE "SITE"). YOUR PRIVACY IS CRUCIAL TO US, AND WE ARE COMMITTED TO
            ENSURING THE SECURITY AND CONFIDENTIALITY OF YOUR PERSONAL DATA.
          </p>
          <h2>1. COLLECTION OF PERSONAL INFORMATION</h2>
          <p>
            UPON YOUR VISIT TO THE SITE, WE AUTOMATICALLY GATHER SPECIFIC
            DETAILS ABOUT YOUR DEVICE. THIS INCLUDES INFORMATION ABOUT YOUR WEB
            BROWSER, IP ADDRESS, TIME ZONE, AND CERTAIN COOKIES INSTALLED ON
            YOUR DEVICE. WHILE YOU EXPLORE THE SITE, WE ALSO CAPTURE INFORMATION
            ABOUT THE SPECIFIC WEB PAGES OR PRODUCTS YOU VIEW, THE WEBSITES OR
            SEARCH TERMS THAT DIRECTED YOU TO OUR PLATFORM, AND DETAILS
            REGARDING YOUR INTERACTIONS WITH THE SITE. THIS
            AUTOMATICALLY-COLLECTED SET OF DATA IS REFERRED TO AS "DEVICE
            INFORMATION."
          </p>
          <p>WE COLLECT DEVICE INFORMATION USING THE FOLLOWING TECHNOLOGIES:</p>
          <ul>
            <li>
              <span className="important">“COOKIES”</span> ARE DATA FILES THAT
              ARE PLACED ON YOUR DEVICE OR COMPUTER AND OFTEN INCLUDE AN
              ANONYMOUS UNIQUE IDENTIFIER. FOR MORE INFORMATION ABOUT COOKIES,
              AND HOW TO DISABLE COOKIES, VISIT{" "}
              <a href="http://www.allaboutcookies.org" target="_blank">
                HTTP://WWW.ALLABOUTCOOKIES.ORG
              </a>
              .
            </li>
            <li>
              <span className="important">“LOG FILES”</span> TRACK ACTIONS
              OCCURRING ON THE SITE, AND COLLECT DATA INCLUDING YOUR IP ADDRESS,
              BROWSER TYPE, INTERNET SERVICE PROVIDER, REFERRING/EXIT PAGES, AND
              DATE/TIME STAMPS.
            </li>
            <li>
              <span className="important">“WEB BEACONS,” “TAGS,”</span> AND{" "}
              <span className="important">“PIXELS”</span> ARE ELECTRONIC FILES
              USED TO RECORD INFORMATION ABOUT HOW YOU BROWSE THE SITE.
            </li>
          </ul>
          <p>
            FURTHERMORE, WHEN YOU ENGAGE IN A PURCHASE OR ATTEMPT TO DO SO
            THROUGH THE SITE, WE GATHER SPECIFIC DETAILS FROM YOU. THIS INCLUDES
            YOUR NAME, BILLING ADDRESS, SHIPPING ADDRESS, AND PAYMENT
            INFORMATION (SUCH AS CREDIT CARD NUMBERS, EMAIL ADDRESS, METAMASK,
            ETH ADDRESS, AND PHONE NUMBER). THIS SET OF INFORMATION IS
            CATEGORIZED AS "ORDER INFORMATION." REST ASSURED, WE HANDLE THIS
            INFORMATION SECURELY AND WITH THE UTMOST RESPECT FOR YOUR PRIVACY.
            OUR COMMITMENT IS TO ENSURE A SECURE AND RELIABLE PURCHASING
            EXPERIENCE FOR YOU ON THE SITE.
          </p>
          <p>
            IN THE CONTEXT OF THIS PRIVACY POLICY, THE TERM "PERSONAL
            INFORMATION" ENCOMPASSES BOTH DEVICE INFORMATION AND ORDER
            INFORMATION. THIS ENSURES TRANSPARENCY IN OUR COMMUNICATION ABOUT
            THE TYPES OF DATA WE COLLECT AND UNDERSCORES OUR COMMITMENT TO
            SAFEGUARDING YOUR PRIVACY ACROSS ALL ASPECTS OF YOUR INTERACTION
            WITH THE SITE.
          </p>
          <h2>2. UTILIZATION OF YOUR PERSONAL INFORMATION:</h2>
          <p>
            THE ORDER INFORMATION WE GATHER SERVES VARIOUS PURPOSES, PRIMARILY
            AIMED AT FULFILLING ORDERS PLACED THROUGH THE SITE. THIS INCLUDES
            PROCESSING PAYMENT DETAILS, COORDINATING SHIPMENT LOGISTICS, AND
            FURNISHING INVOICES AND/OR ORDER CONFIRMATIONS. BEYOND ORDER
            FULFILLMENT, WE USE YOUR ORDER INFORMATION TO ENGAGE IN
            COMMUNICATION WITH YOU EFFECTIVELY. ADDITIONALLY, WE EMPLOY IT TO
            ASSESS ORDERS FOR POTENTIAL RISKS OR FRAUDULENT ACTIVITIES.
            MOREOVER, ALIGNING WITH THE PREFERENCES YOU'VE SHARED WITH US, WE
            MAY FURNISH YOU WITH INFORMATION OR ADVERTISEMENTS PERTINENT TO OUR
            PRODUCTS OR SERVICES.
          </p>
          <p>
            THE DEVICE INFORMATION GATHERED, PARTICULARLY YOUR IP ADDRESS, IS
            UTILIZED TO SCRUTINIZE POTENTIAL RISKS AND FRAUD. MOREOVER, WE
            EMPLOY THIS DATA TO ENHANCE AND OPTIMIZE OUR SITE, SUCH AS BY
            GENERATING ANALYTICS TO UNDERSTAND HOW CUSTOMERS BROWSE AND INTERACT
            WITH THE SITE. THIS INFORMATION IS ALSO INSTRUMENTAL IN EVALUATING
            THE SUCCESS OF OUR MARKETING AND ADVERTISING CAMPAIGNS.
          </p>
          <h2>3. COLLABORATION WITH THIRD PARTIES:</h2>
          <p>
            TO FACILITATE THE UTILIZATION OF YOUR PERSONAL INFORMATION, WE MAY
            COLLABORATE WITH THIRD PARTIES. FOR INSTANCE, WE EMPLOY GOOGLE
            ANALYTICS TO GAIN INSIGHTS INTO HOW OUR CUSTOMERS INTERACT WITH THE
            SITE. FURTHER DETAILS ABOUT HOW GOOGLE HANDLES PERSONAL INFORMATION
            CAN BE FOUND{" "}
            <a href="GooglePrivacyPolicyLink" target="_blank">
              HERE
            </a>
            . ADDITIONALLY, IF YOU WISH TO OPT-OUT OF GOOGLE ANALYTICS, YOU CAN
            DO SO{" "}
            <a href="GoogleAnalyticsOptOutLink" target="_blank">
              HERE
            </a>
            .
          </p>
          <h2>4. TRANSFER OF PRIVACY POLICY AND INFORMATION:</h2>
          <p>
            IN THE COURSE OF VARIOUS EVENTS SUCH AS MERGERS, ACQUISITIONS, OR
            RESTRUCTURING, WE RESERVE THE RIGHT TO TRANSFER OR ASSIGN THIS
            PRIVACY POLICY, ALONG WITH ANY ASSOCIATED PERSONAL INFORMATION, TO A
            THIRD-PARTY ENTITY. THIS MAY INCLUDE SITUATIONS LIKE THE SALE OF A
            SIGNIFICANT PORTION OF OUR SHARES OR ASSETS, BANKRUPTCY PROCEEDINGS,
            OR OTHER CHANGES OF CONTROL. ADDITIONALLY, YOUR PERSONAL INFORMATION
            MAY BE SHARED WHEN NECESSARY TO COMPLY WITH APPLICABLE LAWS AND
            REGULATIONS, RESPOND TO LEGAL REQUESTS SUCH AS SUBPOENAS OR SEARCH
            WARRANTS, OR SAFEGUARD OUR RIGHTS.
          </p>
          <h2>5. TAILORED ADVERTISING:</h2>
          <p>
            AS OUTLINED EARLIER, WE UTILIZE YOUR PERSONAL INFORMATION TO DELIVER
            PERSONALIZED ADVERTISEMENTS OR MARKETING COMMUNICATIONS THAT ALIGN
            WITH YOUR INTERESTS. TO GAIN A DEEPER UNDERSTANDING OF HOW TARGETED
            ADVERTISING OPERATES, YOU CAN EXPLORE THE NETWORK ADVERTISING
            INITIATIVE'S ("NAI") EDUCATIONAL PAGE FOR MORE INSIGHTS.
          </p>
          <p>
            YOU CAN OPT OUT OF CERTAIN TARGETED ADVERTISING BY FOLLOWING THE
            INSTRUCTIONS AT THESE SITES:
          </p>
          <ul>
            <li>
              <a
                href="https://www.facebook.com/settings/?tab=ads"
                target="_blank"
              >
                Facebook - https://www.facebook.com/settings/?tab=ads
              </a>
            </li>
            <li>
              <a
                href="https://www.google.com/settings/ads/anonymous"
                target="_blank"
              >
                Google - https://www.google.com/settings/ads/anonymous
              </a>
            </li>
          </ul>
          <p>
            ADDITIONALLY, YOU CAN OPT OUT OF SOME OF THESE SERVICES BY VISITING
            THE DIGITAL ADVERTISING ALLIANCE'S OPT-OUT PORTAL AT:{" "}
            <a href="http://optout.aboutads.info/" target="_blank">
              HTTP://OPTOUT.ABOUTADS.INFO/
            </a>
            .
          </p>
          <h2>6. RESPECTING DO NOT TRACK SIGNALS:</h2>
          <p>
            IT'S IMPORTANT TO BE AWARE THAT WE DO NOT MODIFY OUR SITE'S DATA
            COLLECTION AND USAGE PRACTICES IN RESPONSE TO A DO NOT TRACK SIGNAL
            FROM YOUR BROWSER.
          </p>
          <h2>7. YOUR RIGHTS AS A EUROPEAN RESIDENT:</h2>
          <p>
            AS A EUROPEAN RESIDENT, YOU HOLD THE RIGHT TO ACCESS THE PERSONAL
            INFORMATION WE HAVE ABOUT YOU AND CAN REQUEST CORRECTIONS, UPDATES,
            OR DELETIONS TO THAT INFORMATION. SHOULD YOU WISH TO EXERCISE THIS
            RIGHT, PLEASE CONTACT US USING THE INFORMATION PROVIDED BELOW.
          </p>
          <p>
            IT IS IMPORTANT TO ACKNOWLEDGE THAT IF YOU ARE A EUROPEAN RESIDENT,
            WE PROCESS YOUR INFORMATION TO FULFILL CONTRACTS WE MAY HAVE WITH
            YOU (SUCH AS WHEN YOU PLACE AN ORDER THROUGH THE SITE) OR FOR OUR
            LEGITIMATE BUSINESS INTERESTS, AS OUTLINED ABOVE. ADDITIONALLY,
            PLEASE BE AWARE THAT YOUR INFORMATION MAY BE TRANSFERRED OUTSIDE OF
            EUROPE, INCLUDING TO CANADA AND THE UNITED STATES.
          </p>
          <h2>DATA RETENTION</h2>
          <p>
            WHEN YOU PLACE AN ORDER THROUGH THE SITE, WE WILL MAINTAIN YOUR
            ORDER INFORMATION FOR OUR RECORDS UNLESS AND UNTIL YOU ASK US TO
            DELETE THIS INFORMATION.
          </p>

          <h2>8. MINORS</h2>
          <p>
            THE SITE IS NOT INTENDED IN ANY WAY FOR INDIVIDUALS UNDER THE AGE OF
            18.
          </p>
          <h2>9. CHANGES TO THE PRIVACY POLICY:</h2>
          <p>
            THIS PRIVACY POLICY MAY BE PERIODICALLY UPDATED TO INCORPORATE
            CHANGES TO OUR PRACTICES OR FOR OPERATIONAL, LEGAL, OR REGULATORY
            REASONS.
          </p>
          <h2>CONTACT US</h2>
          <p>
            FOR MORE INFORMATION ABOUT OUR PRIVACY PRACTICES, IF YOU HAVE
            QUESTIONS, OR IF YOU WOULD LIKE TO MAKE A COMPLAINT, PLEASE CONTACT
            US BY E-MAIL AT [EMAIL] OR BY REGISTERED MAIL USING THE DETAILS
            PROVIDED BELOW:
          </p>
          <p>[•].</p>
        </div>
      </center>
    </>
  );
}

export default index